<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Bootstrap 3, from LayoutIt!</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /-->
        <!--link rel="stylesheet/less" href="less/responsive.less" type="text/css" /-->
        <!--script src="js/less-1.3.3.min.js"></script-->
        <!--append ‘#!watch’ to the browser URL, then refresh the page. -->

        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="img/favicon.png">

        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <script type="text/javascript" src="js/scripts.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row clearfix">
                <div class="row clearfix">
                    <div class="col-md-12 column">

                    </div>
                </div>
                <div class="col-md-12 column">
                    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav navbar-nav">
                                    <li><a class="brand" href="#">TM Estimates</a></li>
                                    <li class="active">
                                        <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Início</a>
                                    </li>
                                    <li class=""><a href="#">Sobre</a></li>
                                    <li class=""><a href="#">Pacotes</a></li>
                                </ul>
                                <ul class="nav navbar-nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Acesso<strong class="caret"></strong></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'login', 'action' => 'index'), null, true) ?>">Login</a>
                                            </li>
                                            <li>
                                                <a href="#">Cadastro</a>
                                            </li>
                                        </ul>
                                    </li>		
                                </ul>
                                <li>
                                    <div class="btn-group">

                                    </div>
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
              </div>

 <div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">              
              <div id="myCarousel" class="carousel slide">
                <div class="carousel-inner">
                  <div class="item active">
                    <img src="img/desen.jpg" alt="">
                    <div class="carousel-caption">
                      <h4>O que é?</h4>
                      <p>O TM Estimates tem como objetivo auxiliar no desenvolvimento de softwares, estimando tempo, custo, recursos que serão necessários ao longo do projeto.</p>
                    </div>
                  </div>
                  <div class="item">
                    <img src="img/Agi.jpg" alt="">
                    <div class="carousel-caption">
                      <h4>Como funciona?</h4>
                      <p>A partir de dados oferecidos pelo cliente, o site irá gerar estimativas, da mesma forma poderão ser gerados gráficos a partir da segunda estimativa do projeto e notificações para os usuários cadastrados(não administradores) via email.</p>
                    </div>
                  </div>
                  <div class="item">
                    <img src="img/pree.jpg" alt="">
                    <div class="carousel-caption">
                      <h4>Porque usar?</h4>
                      <p>Uma das principais partes do projeto é saber quanto tempo ele irá demorar para ser desenvolvido, quanto custará e quanto de esforço deverá ser aplicado, para que tenha um equilíbrio entre os três fatores é preciso ou ser expert em estimativas ou trabalhar com softwares que façam isso para você, pensando nisso a empresa Estimatech desenvolverá um software capaz de estimar de uma forma que seja adequada para o problema do cliente.</p>
                    </div>
                  </div>
                  <div class="item">
                    <img src="img/equi.jpg" alt="">
                    <div class="carousel-caption">
                      <h4>Sobre a empresa</h4>
                      <p>A empresa conta com uma equipe jovem e muito bem formada, com experiência em diversas áreas, tais como: Conhecimento em bancos de dados SQL Server, MySQL, linguagens de programação Java, C, C#, PHP, Design usando CorelDRAW, experiência com computadores de alta performance e experiência na Unidade de Desenvolvimento Organizacional da UESC.</p>
                    </div>
                  </div>
                </div>
                    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
            </div>

        </div>
    </div>
</div>
            <!-- <div class="row clearfix top-buffer">
                <div class="col-md-12 column">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <p class="text-center"> Estimatch </p>
            
                </div>
            </div> -->
        <!-- </div> -->
    </body> 
</html>