<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Bootstrap 3, from LayoutIt!</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /-->
        <!--link rel="stylesheet/less" href="less/responsive.less" type="text/css" /-->
        <!--script src="js/less-1.3.3.min.js"></script-->
        <!--append ‘#!watch’ to the browser URL, then refresh the page. -->

        
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="img/favicon.png">

        <script type="text/javascript" src="/TM-Estimates/public/js/jquery.min.js"></script>
        <script type="text/javascript" src="/TM-Estimates/public/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/TM-Estimates/public/js/scripts.js"></script>
        <script type="text/javascript" src="/TM-Estimates/public/js/funcoes.js"></script>

    </head>
    <body>
        <div class="container">
            <div class="row clearfix">
                <div class="row clearfix">
                    <div class="col-md-12 column">

                    </div>
                </div>
                <div class="col-md-12 column">
                    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav navbar-nav">
                                    <li><a class="brand" href="#">TM Estimates</a></li>
                                    <li class="active">
                                        <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Início</a>
                                    </li>
                                    <li class=""><a href="#">Sobre</a></li>
                                    <li class=""><a href="#">Pacotes</a></li>
                                </ul>
                                <ul class="nav navbar-nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Acesso<strong class="caret"></strong></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'login', 'action' => 'index'), null, true) ?>">Login</a>
                                            </li>
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'cadastro-user', 'action' => 'index'), null, true) ?>">Cadastro</a>
                                            </li>
                                        </ul>
                                    </li>		
                                </ul>
                                <li>
                                    <div class="btn-group">

                                    </div>
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            
            <div class="row-fluid clearfix top-buffer">
                
                    <?php echo $this->layout()->content; ?>
               
            </div>
            <div class="panel-footer text-center"><b>© Copyright 2014 - by Estimatech</b></div>
        </div>
    </div> 
</body> 
</html>