<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Estimatech">

        <title>TM-Estimates</title>

        <!-- Bootstrap -->
        <link href="/TM-Estimates/public/css/bootstrap.min.css" rel="stylesheet">

        <!-- Carousel -->
        <link href="/TM-Estimates/public/css/bootcarouselmark.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="img/favicon.png">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav navbar-nav">
                                    <li><a class="brand" href="#">TM Estimates</a></li>
                                    <li class="active">
                                        <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Início</a>
                                    </li>
                                    <li class=""><a href="<?= $this->url(array('controller' => 'index', 'action' => 'sobre'), null, true) ?>">Sobre</a></li>
                                    <li class=""><a href="<?= $this->url(array('controller' => 'index', 'action' => 'pacotes'), null, true) ?>">Pacotes</a></li>
                                </ul>
                                <ul class="nav navbar-nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Acesso<strong class="caret"></strong></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'login', 'action' => 'index'), null, true) ?>">Login</a>
                                            </li>
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'cadastro-user', 'action' => 'index'), null, true) ?>">Cadastro</a>
                                            </li>
                                        </ul>
                                    </li>		
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid clearfix top-buffer">

                <?php echo $this->layout()->content; ?>

            </div>
        </div>

        <br/>
        <br/>
        <br/>
        <br/>

        <!--<div class="panel-footer text-center"><b>© Copyright 2014 - by Estimatech</b></div>-->
        <div id="footer" class="container">
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="navbar-inner navbar-content-center col-md-offset-5">
                    <p class="navbar-text">
                        © Copyright 2014 - by <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Estimatech</a>.
                    </p>
                </div>
            </nav>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="/TM-Estimates/public/js/bootstrap.min.js"></script>
        <script src="/TM-Estimates/public/js/jquery.maskedinput.min.js"></script>
        <script type="text/javascript" src="/TM-Estimates/public/js/scripts.js"></script>
        <script type="text/javascript" src="/TM-Estimates/public/js/funcoes.js"></script> 
    </body> 
</html>