<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>TM Estimatch</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" type="text/css" href="/TM-Estimates/public/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/TM-Estimates/public/css/bootextra.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/TM-Estimates/public/js/bootstrap.min.js"></script>
        <script src="/TM-Estimates/public/js/jquery.maskedinput.min.js"></script>
        <script src="/TM-Estimates/public/js/jquery.price_format.2.0.min.js"></script>
        <script src="/TM-Estimates/public/js/scripts.js"></script>

    </head>
    <body>
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav navbar-nav">
                                    <li><a class="brand" href="#">TM Estimates</a></li>
                                    <li class="active">
                                        <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Início</a>
                                    </li>
                                    <li class=""><a href="<?= $this->url(array('controller' => 'index', 'action' => 'sobre'), null, true) ?>">Sobre</a></li>
                                    <li class=""><a href="<?= $this->url(array('controller' => 'index', 'action' => 'pacotes'), null, true) ?>">Pacotes</a></li>
                                </ul>
                                <ul class="nav navbar-nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><?= $this->email ?><strong class="caret"></strong></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'user', 'action' => 'index'), null, true) ?>">Painel</a>
                                            </li>
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'preferencias', 'action' => 'index'), null, true) ?>">Preferências</a>
                                            </li>
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'login', 'action' => 'logout'), null, true) ?>">Sair</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class=""><a href="<?= $this->url(array('controller' => 'contato', 'action' => 'index'), null, true) ?>">Contado</a></li>
                                </ul>
                                <li>
                                    <div class="btn-group">

                                    </div>
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row affix-row top-buffer">

            <!-- Menu Lateral-->

            <div class="col-sm-3 col-md-2 affix-sidebar">
                <div class="sidebar-nav">
                    <div class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <span class="visible-xs navbar-brand">Sidebar menu</span>
                        </div>
                        <div class="navbar-collapse collapse sidebar-navbar-collapse">
                            <ul class="nav navbar-nav" id="sidenav01">
                                <li class="active">
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01" class="collapsed">
                                        <h4>
                                            Painel de controle
                                            <br>
                                            <small>Colaboradores <span class="caret"></span></small>
                                        </h4>
                                    </a>
                                    <div class="collapse" id="toggleDemo0" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'administradores', 'action' => 'novo'), null, true) ?>">Novo</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'administradores', 'action' => 'index'), null, true) ?>">Listar</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01" class="collapsed">
                                        <span class="glyphicon glyphicon-inbox"></span> Arquivo <span class="caret pull-right"></span>
                                    </a>
                                    <div class="collapse" id="toggleDemo" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'projeto', 'action' => 'index'), null, true) ?>">Projeto</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'fase', 'action' => 'index'), null, true) ?>">Fase</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'recurso', 'action' => 'index'), null, true) ?>">Recurso</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'equipe', 'action' => 'index'), null, true) ?>">Equipe</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="active">
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo2" data-parent="#sidenav01" class="collapsed">
                                        <span class="glyphicon glyphicon-file"></span> Análise <span class="caret pull-right"></span>
                                    </a>
                                    <div class="collapse" id="toggleDemo2" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'FuncaoDados', 'action' => 'index'), null, true) ?>">Funções de Dados</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'FuncaoTransacao', 'action' => 'index'), null, true) ?>">Funções de Transação</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'itens-influencia', 'action' => 'index'), null, true) ?>">Itens de Influência</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'Contagem', 'action' => 'index'), null, true) ?>">Contagem</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo3" data-parent="#sidenav01" class="collapsed">
                                        <span class="glyphicon glyphicon-th"></span> Detalhar <span class="caret pull-right"></span>
                                    </a>
                                    <div class="collapse" id="toggleDemo3" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'Detalhar', 'action' => 'fases'), null, true) ?>">Fases</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'Detalhar', 'action' => 'custos'), null, true) ?>">Custos</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="active">
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo4" data-parent="#sidenav01" class="collapsed">
                                        <span class="glyphicon glyphicon-usd"></span> Estimar <span class="caret pull-right"></span>
                                    </a>
                                    <div class="collapse" id="toggleDemo4" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'EstimarCusto', 'action' => 'index'), null, true) ?>"> Custos</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'estimar-esforco', 'action' => 'index'), null, true) ?>"> Esforço</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'estimar-prazo', 'action' => 'index'), null, true) ?>"> Prazo</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'estimar-produtividade', 'action' => 'index'), null, true) ?>"> Produtividade</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'pontos-funcao', 'action' => 'index'), null, true) ?>"> Pontos de Função</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li><a href="<?= $this->url(array('controller' => 'relatorio', 'action' => 'index'), null, true) ?>"><span class="glyphicon glyphicon-book"></span> Relatório</a></li>
                                <li><a href="<?= $this->url(array('controller' => 'calendario', 'action' => 'index'), null, true) ?>"><span class="glyphicon glyphicon-calendar"></span> Calendário</a></li>
                                <li><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'editar-user'), null, true) ?>"><span class="glyphicon glyphicon-cog"></span> Preferências</a></li>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- Corpo -->
            <div class="col-sm-9 col-md-10 affix-content">
                <?php
                echo $this->layout()->content;
                ?> 
            </div>
        </div>

        <div id="footer" class="container">
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="navbar-inner navbar-content-center col-md-offset-5">
                    <p class="navbar-text">
                        © Copyright 2014 - by <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Estimatech</a>.
                    </p>
                </div>
            </nav>
        </div>
    </body>
</html>
