<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>TM Estimatch</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" type="text/css" href="/TM-Estimates/public/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/TM-Estimates/public/css/bootextra.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="/TM-Estimates/public/js/bootstrap.min.js"></script>
        <script src="/TM-Estimates/public/js/scripts.js"></script>

    </head>
    <body>
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav navbar-nav">
                                    <li><a class="brand" href="#">TM Estimates</a></li>
                                    <li class="active">
                                        <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Início</a>
                                    </li>
                                    <li class=""><a href="#">Sobre</a></li>
                                    <li class=""><a href="#">Pacotes</a></li>
                                </ul>
                                <ul class="nav navbar-nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Acesso<strong class="caret"></strong></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="<?= $this->url(array('controller' => 'login', 'action' => 'index'), null, true) ?>">Login</a>
                                            </li>
                                            <li>
                                                <a href="#">Cadastro</a>
                                            </li>
                                        </ul>
                                    </li>		
                                </ul>
                                <li>
                                    <div class="btn-group">

                                    </div>
                                </li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row affix-row top-buffer">

            <!-- Menu Lateral-->

            <div class="col-sm-3 col-md-2 affix-sidebar">
                <div class="sidebar-nav">
                    <div class="navbar navbar-default" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <span class="visible-xs navbar-brand">Sidebar menu</span>
                        </div>
                        <div class="navbar-collapse collapse sidebar-navbar-collapse">
                            <ul class="nav navbar-nav" id="sidenav01">
                                <li class="active">
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01" class="collapsed">
                                        <h4>
                                            Control Panel
                                            <br>
                                            <small>Admins <span class="caret"></span></small>
                                        </h4>
                                    </a>
                                    <div class="collapse" id="toggleDemo0" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'administradores', 'action' => 'index'), null, true) ?>">Listar</a></li>
                                            <li><a href="#">Novo</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'administradores', 'action' => 'gerenciar'), null, true) ?>">Gerenciar</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01" class="collapsed">
                                        <span class="glyphicon glyphicon-cloud"></span> Arquivo <span class="caret pull-right"></span>
                                    </a>
                                    <div class="collapse" id="toggleDemo" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="<?= $this->url(array('controller' => 'projeto', 'action' => 'index'), null, true) ?>">Projeto</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'ambiente', 'action' => 'index'), null, true) ?>">Ambiente</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'recurso', 'action' => 'index'), null, true) ?>">Recurso</a></li>
                                            <li><a href="<?= $this->url(array('controller' => 'equipe', 'action' => 'index'), null, true) ?>">Equipe</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="active">
                                    <a href="#" data-toggle="collapse" data-target="#toggleDemo2" data-parent="#sidenav01" class="collapsed">
                                        <span class="glyphicon glyphicon-inbox"></span> Análise <span class="caret pull-right"></span>
                                    </a>
                                    <div class="collapse" id="toggleDemo2" style="height: 0px;">
                                        <ul class="nav nav-list">
                                            <li><a href="#">Funções de Dados</a></li>
                                            <li><a href="#">Funções de Transação</a></li>
                                            <li><a href="#">Itens de Influência</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li><a href="#"><span class="glyphicon glyphicon-lock"></span> Normalmenu</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-calendar"></span> Calendário <span class="badge pull-right">42</span></a></li>
                                <li><a href=""><span class="glyphicon glyphicon-cog"></span> Preferências</a></li>
                            </ul>
                        </div><!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!-- Corpo -->
            <div class="col-sm-9 col-md-10 affix-content">
                <?php
                echo $this->layout()->content;
                ?> 
            </div>
        </div>

        <div id="footer" class="container">
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="navbar-inner navbar-content-center col-md-offset-5">
                    <p class="navbar-text">
                        © Copyright 2014 - by <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>">Estimatech</a>.
                    </p>
                </div>
            </nav>
        </div>
    </body>
</html>
