<br /><br />
<div id="view-content">
    <br /><br /><br /><br /><br /><br />
    <div id="view-content">
        <div class="row clearfix top-buffer">
            <div class="col-md-8">
                <div class="col-md-offset-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>Esqueceu senha</strong></h3>
                        </div>
                        <div class="panel-body">
                            <form role="form" >
                                <div class="form-group text-center">
                                    <label><h3>Sua solicitação expirou!</h3></label>
                                    <br>
                                    <label>Verifique se não foi feita uma nova solicitação ou se sua solicitação foi feita
                                        a mais de 24 horas, se não foi feita uma nova solicitação então solicite novamente o
                                        email de redefinição.</label>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>