<br /><br />
<div id="view-content">
	<br /><br /><br /><br /><br /><br />
<div id="view-content">
<div class="row clearfix top-buffer">
            <div class="col-md-8">
                <div class="col-md-offset-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Esqueceu senha</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'Esqueceu-Senha', 'action' => 'enviar-Email'), null, true) ?>">
                            <div class="form-group">
                                <label for="Email">Email</label>
                                <input type="email" class="form-control" id="Email" name="Email" placeholder="Digite seu email">
                            </div>
                            <button type="submit" class="btn btn-primary btn-default">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>