<br /><br />
<div id="view-content">
	<br /><br /><br /><br /><br /><br />
<div id="view-content">
<div class="row clearfix top-buffer">
            <div class="col-md-8">
                <div class="col-md-offset-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Esqueceu senha</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" name="Email" placeholder="Enter email">
                            </div>
                            <button type="submit" class="btn btn-primary btn-default">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>