<br /><br />
<div id="view-content">
    <br /><br /><br /><br /><br /><br />
    <div id="view-content">
        <div class="row clearfix top-buffer">
            <div class="col-md-8">
                <div class="col-md-offset-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>Esqueceu senha</strong></h3>
                        </div>
                        <div class="panel-body">
                            <form role="form" >
                                <div class="form-group text-center">
                                    <label><h3>Email não cadastrado!</h3></label>
                                </div>
                                <div class="col-md-8">
                                <div class="col-md-offset-7">
                                    <a href="<?= $this->url(array('controller' => 'esqueceu-senha', 'action' => 'index'), null, true) ?>" class="btn btn-primary btn-block" role="button">Voltar</a>
                                </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>