<br/><br/><br/>
<div class="page-header top-buffer">
    <h3><span class=""></span> Recuperar Senha</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form role="form"  method="post" action="<?= $this->url(array('controller' => 'esqueceu-senha', 'action' => 'salvar-senha'), null, true) ?>">
                        <div class="form-row col-md-12 form-group">
                            <label for="senha">Nova Senha</label>
                            <input type="password" class="form-control" id="senha" name="Senha" placeholder="Password">
                        </div>
                        <div class="form-row col-md-12 form-group">
                            <label for="senha2">Confirme a senha</label>
                            <input type="password" class="form-control" id="senha2" name="ConfSenha" placeholder="Confirme a senha">
                        </div>
                        <div class="form-row col-md-12 form-group">
                            <button type="submit" class="btn btn-success btn-default">Confirmar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

