<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Equipe</h3>
</div>
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'equipe', 'action' => 'novo'), null, true) ?>" class="btn btn btn-success" role="button">Novo</a>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>Projeto</th>
                    <th>Recurso</th>
                    <th>Quantidade de Recursos</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados AS $key => $equipe): ?>
                    <tr>
                        <td><?= $equipe['Recursos_idRecursos'] ?></td>
                        <td><?= $equipe['Projeto_idProjeto'] ?></td>
                        <td><?= $equipe['QtRecursos'] ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'equipe', 'idP' => $equipe['Recursos_idRecursos']), null, true) ?>">Editar</a></td>
                        <td><a>Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
