<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Nova Equipe</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Equipe</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Projeto</label>
                                    <input type="text" class="form-control" id="exampleInputProj" placeholder="Projeto">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Função</label>
                                    <input type="text" class="form-control" id="exampleInputFunc" placeholder="Função">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Quantidade</label>
                                    <input type="number" class="form-control" id="exampleInputQuant" placeholder="Quantidade">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'equipe', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>