<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Nova Equipe</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Equipe</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'equipe', 'action' => 'salvar-dados'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Projeto</label>
                                    <select class="form-control" name="Projeto">
                                        <option value  = "" class="form-control"> </option>
                                        <?php foreach ($this->dados1 as $key => $value) { ?>
                                            <option value="<?= $value["idProjeto"] ?>" class="form-control"> <?= $value['Titulo'] ?> </option>
                                        <?php } ?>
                                    </select>
                                    <!--<input type="" class="form-control" id="exampleInputProj" placeholder="Projeto">-->
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Recurso</label>
                                    <select class="form-control" name="Recurso">
                                        <option value  = "" class="form-control"> </option>
                                        <?php foreach ($this->dados as $key => $value) { ?>
                                            <option value="<?= $value["idRecursos"] ?>" class="form-control"> <?= $value['Descricao'] ?> </option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Quantidade de Recursos</label>
                                    <input type="number" class="form-control" id="exampleInputQuant" name="QtdRec" placeholder="Quantidade">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'equipe', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>