<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Editar Ambiente</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Ambiente</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'editar', 'action' => 'atualiza-am'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Linguagem</label>
                                    <input type="text" class="form-control" id="exampleInputLing" name="Linguagem" placeholder="Linguagem"  value="<?=$this->dados_cliente[0]['Linguagem']?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Esforço(H/PF)</label>
                                    <input type="" class="form-control" id="exampleInputHorPes" name="HorPes" placeholder="Horas por ponto de função"  value="<?=$this->dados_cliente[0]['Esforco']?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Produtividade(PF/H)</label>
                                    <input type="text" class="form-control" id="exampleInputPesH" name="PesH" placeholder="Ponto de função/Hora"  value="<?=$this->dados_cliente[0]['Produtividade']?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <input type = "hidden" name="id" value ="<?= $this->id ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Atualizar</button>
                                    <a href="<?= $this->url(array('controller' => 'ambiente', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

