<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span>Editar Detalhes da Fase</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Fase</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'editar', 'action' => 'atualiza-dt-fa'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Descrição</label>
                                    <input required type="text" class="form-control" id="exampleInputDesc" name="Desc" placeholder="Descrição" value="<?= $this->dados_cliente[0]['Descricao'] ?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Percentual</label>
                                    <input required type="number" class="form-control" id="exampleInputPer" name="Percentual" placeholder="Percentual" value="<?= $this->dados_cliente[0]['Percentual'] ?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. início (Prevista)</label>
                                    <input type="" class="form-control" id="exampleInputDatIniPr" name="DatIniPre" value="<?= $this->dados_cliente[0]['datIniPrev'] ?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. Finalização (Prevista)</label>
                                    <input type="" class="form-control" id="exampleInputDtFinPr" name="DatFinPre" value="<?= $this->dados_cliente[0]['datFinPrev'] ?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. início (Efetiva)</label>;
                                    <input type="" class="form-control" id="exampleInputdtIniEf" name="DatIniEfe" value="<?= $this->dados_cliente[0]['datIniEfet'] ?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. Finalização (Efetiva)</label>;
                                    <input type="" class="form-control" id="exampleInputdtFinEf" name="DatFinEfe" value="<?= $this->dados_cliente[0]['datFinEfet'] ?>">
                                </div>
                            </div>
                            <input type = "hidden" name="id" value ="<?= $this->id ?>">
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Atualizar</button>
                                    <a href="<?= $this->url(array('controller' => 'Detalhar', 'action' => 'fases'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

