<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Editar Equipe</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Equipe</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'editar', 'action' => 'atualiza-eq'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Projeto</label>
                                    <span class="form-control" name="idProjeto" value="<?= $this->dados_cliente[0]['Projeto_idProjeto'] ?>">
                                        <?= $this->dados_cliente[0]['Projeto_idProjeto'] ?>
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Recurso</label>
                                    <span class="form-control" name="idRecurso" value="<?= $this->dados_cliente[0]['Recursos_idRecursos'] ?>">
                                        <?= $this->dados_cliente[0]['Recursos_idRecursos'] ?>
                                    </span>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Quantidade de Recursos</label>
                                    <input required type="number" class="form-control" id="exampleInputQuant" name="QtdRec" placeholder="Quantidade" value="<?= $this->dados_cliente[0]['QtRecursos'] ?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <input type = "hidden" name="id" value ="<?= $this->id ?>">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-default">Atualizar</button>
                                    <a href="<?= $this->url(array('controller' => 'equipe', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>