<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Editar Função de dados</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Função de dados</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'editar', 'action' => 'atualizar-fd'), null, true) ?>">
                            <div class="col-md-6 form-groups">
                                <label>Função</label>
                                <select required class="form-control" name="funcao">
                                    <option value  = "ALI" class="form-control" <?php if($this->dados[0]['Funcao'] == 'ALI') echo 'selected'; else '';?>> ALI </option>
                                    <option value = "AIE" class="form-control" <?php if($this->dados[0]['Funcao'] == 'AIE') echo 'selected'; else '';?>> AIE </option>
                                </select>
                            </div>

                            <div class="col-md-6">
                                <div required class="col-md-offset-0">
                                    <label>Descrição</label>
                                    <input type="text" class="form-control" id="exampleInputDesc" name="Descri" placeholder="Descrição" value="<?= $this->dados[0]['Descricao'] ?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-6">
                                <div class="col-md-offset-0">
                                    <label>Qtd. Tipos de registro</label>
                                    <input required type="number" class="form-control" id="exampleInputTipReg" name="TipRegis" placeholder="Quantidade de Tipos de registro" value="<?= $this->dados[0]['qtdTiposRegistro'] ?>">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-offset-0">
                                    <label>Qtd. Tipos de dados</label>
                                    <input required type="number" class="form-control" id="exampleInputTipDad" name="TipDados" placeholder="Quantidades de Tipos de dados" value="<?= $this->dados[0]['qtdTiposDados'] ?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <input type = "hidden" name="id" value ="<?= $this->id ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Atualizar</button>

                                    <a href="<?= $this->url(array('controller' => 'funcao-dados', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

