<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Editar Projeto</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Projeto</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'projeto', 'action' => 'salvar-Dados'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="NomeProjeto">Nome Projeto</label>
                                    <input type="text" class="form-control"  name="projetoTitulo" placeholder="Insira Nome Projeto" value="<?=$this->dados_cliente[0]['Titulo']?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="DataCricao">Data da Criação</label>
                                    <input type="" class="form-control" name="projetoDataCriacao" value="<?=$this->dados_cliente[0]['DataCriacao']?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="DataFim">Data da Finalização</label>
                                    <input type="" class="form-control" name="projetoDataFim" value="<?=$this->dados_cliente[0]['DataFininalizacao']?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="situacao">Categoria</label>
                                    <select class="form-control" name="projetoCategoria">
                                        <option selected="" value="DESENVOLVIMENTO">Desenvolvimento</option>
                                        <option value="MELHORIA" >Melhoria</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="situacao">Situação</label>
                                    <select class="form-control" name="projetoSituacao" value="<?=$this->dados_cliente[0]['Situacao']?>">
                                        <option selected="" value="A">Andamento</option>
                                        <option value="F" >Finalizado</option>
                                    </select>
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Atualizar</button>
                                    <a href="<?= $this->url(array('controller' => 'projeto', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

