<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Editar Itens de influência</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Itens de influência</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'ambiente', 'action' => 'salvar-dados'), null, true) ?>">
                            <div class="col-md-4 form-groups">
                                <label>Comunicação de dados</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Processamento distribuído</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>

                            <div class="col-md-4 form-groups">
                                <label>Performace</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4 form-groups">
                                <label>Config. altamente utilizada</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Faixa de transações</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>

                            <div class="col-md-4 form-groups">
                                <label>Entrada de dados On-Line</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4 form-groups">
                                <label>Eficiência do usuário final</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Atualização On-Line</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>

                            <div class="col-md-4 form-groups">
                                <label>Complexidade processamento</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4 form-groups">
                                <label>Reutilização</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Facilidade de instalação</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>

                            <div class="col-md-4 form-groups">
                                <label>Facilidade de operação</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4 form-groups">
                                <label>Multiplas localidades</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>

                            <div class="col-md-4 form-groups">
                                <label>Facilidade de mudanças</label>
                                <select required class="form-control">
                                    <option value  = "0" class="form-control text-center">0</option>
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'itens-influencia', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

