<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Editar Recurso</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Recurso</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'recurso', 'action' => 'salvar-dados'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Função</label>
                                    <input type="text" class="form-control" name="descricao" placeholder="Função" value="<?=$this->dados_cliente[0]['Descricao']?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Carga Horária/Dia</label>
                                    <input type="number" class="form-control" name="carga_horaria" placeholder="0" value="<?=$this->dados_cliente[0]['Carga_horaria']?>">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Custo/Hora</label>
                                    <input type="" class="form-control" id="custo" name="custo" value="<?=$this->dados_cliente[0]['Carga_horaria']?>">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'recurso', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

