<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Estimativas de Produtividade</h3>
</div>
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'estimar-produtividade', 'action' => 'gerar-produtividade'), null, true) ?>" class="btn btn btn-success" role="button">Novo</a>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Data</th>
                    <th>Projeto</th>
                    <th>Estimativa</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->produtividade AS $key => $produtividade): ?>
                    <tr>
                        <td><?= $produtividade['idEstimativasProdutividade'] ?></td>
                        <td><?= $produtividade['Data'] ?></td>
                        <td><?= $produtividade['projeto_idProjeto'] ?></td>
                        <td><?= $produtividade['Estimativa'] ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'estimar-produtividade', 'action' => 'excluir', 'idP' => $produtividade['idEstimativasProdutividade']), null, true) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
