<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Gerar relatório</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Gerar relatório</strong></h3>
                </div>
                <div class="panel-body">
                    <form role="form" >
                                                <div class="col-md-12">
                            <div class="form-group">
                                <label>Projeto</label>
                                <select required class="form-control" name="Projeto">
                                    <option value  = "" class="form-control"> </option>
                                    <?php foreach ($this->dados1 as $key => $value) { ?>
                                        <option value="<?= $value["idProjeto"] ?>" class="form-control"> <?= $value['Titulo'] ?> </option>
                                    <?php } ?>
                                </select>
                                <!--<input type="" class="form-control" id="exampleInputProj" placeholder="Projeto">-->
                            </div>
                        </div>
                        <br><br><br><br>
                        <div class="col-md-12">
                           <a target=_blank href="<?= $this->url(array('controller' => 'relatorio', 'action' => 'relatorio'), null, true) ?>" class="btn btn-success btn-block" role="button">Gerar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

