<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Gerar relatório</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Gerar relatório</strong></h3>
                </div>
                <div class="panel-body">
                    <form role="form" >
                        <div class="col-md-12">
                           <a target=_blank href="<?= $this->url(array('controller' => 'relatorio', 'action' => 'relatorio'), null, true) ?>" class="btn btn-success btn-block" role="button">Gerar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

