
<!-- Chamando css -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>TM Estimatch</title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/bootextra.css" rel="stylesheet">
    </head>
    <body>
<div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="img/desen.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>O que é?</h1>
              <p class="lead">O TM Estimates tem como objetivo auxiliar no desenvolvimento de softwares, estimando tempo, custo, recursos que serão necessários ao longo do projeto.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="img/pree.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Como funciona?</h1>
              <p class="lead">A partir de dados oferecidos pelo cliente, o site irá gerar estimativas, da mesma forma poderão ser gerados gráficos a partir da segunda estimativa do projeto e notificações para os usuários cadastrados(não administradores) via email.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="img/Agi.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Porque usar?</h1>
              <p class="lead">Uma das principais partes do projeto é saber quanto tempo ele irá demorar para ser desenvolvido, quanto custará e quanto de esforço deverá ser aplicado, para que tenha um equilíbrio entre os três fatores é preciso ou ser expert em estimativas ou trabalhar com softwares que façam isso para você, pensando nisso a empresa Estimatech desenvolverá um software capaz de estimar de uma forma que seja adequada para o problema do cliente.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="img/equi.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Sobre a empresa</h1>
              <p class="lead">A empresa conta com uma equipe jovem e muito bem formada, com experiência em diversas áreas, tais como: Conhecimento em bancos de dados SQL Server, MySQL, linguagens de programação Java, C, C#, PHP, Design usando CorelDRAW, experiência com computadores de alta performance e experiência na Unidade de Desenvolvimento Organizacional da UESC.</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel --> 

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
          <img class="img-circle" src="img/pacbasic.jpg">
          <h2>Básico</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
          <p><a class="btn" href="#">Compre Aqui! &raquo;</a></p>
        </div><!-- /.span4 -->
        <div class="span4">
          <img class="img-circle" src="img/pacinter.jpg">
          <h2>Intermediário</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">Compre Aqui! &raquo;</a></p>
        </div><!-- /.span4 -->
        <div class="span4">
          <img class="img-circle" src="img/pacpremium.jpg">
          <h2>Premium</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">Compre Aqui! &raquo;</a></p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->
    </body>
</html>