<br /><br />
<div id="view-content">
    <div class="container marketing">

        <br><br><br><br>
        <div class="row-fluid">
            <div class="col-md-4">
                <div class="img-test">
                    <img src="/TM-Estimates/public/img/pacbasic.jpg" alt="">
                </div>
                <h2>Básico</h2>
                <div class="text-justify">
                    <p>O pacote básico fornecerá acesso a um administrador, podendo cadastrar até três projetos. </p>
                </div>
                <p><a class="btn" href="<?= $this->url(array('controller' => 'vendas', 'action' => 'index'), null, true) ?>">Compre Aqui! &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <div class="img-test">
                    <img src="/TM-Estimates/public/img/pacinter.jpg" alt="">
                </div>
                <h2>Intermediário</h2>
                <div class="text-justify">
                    <p>O pacote intermediário fornecerá acesso a três administradores, podendo cadastrar até oito projetos. </p>
                </div>
                <p><a class="btn" href="<?= $this->url(array('controller' => 'vendas', 'action' => 'index'), null, true) ?>">Compre Aqui! &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <div class="img-test">
                    <img src="/TM-Estimates/public/img/pacpremium.jpg" alt="">
                </div>
                <h2>Premium</h2>
                <div class="text-justify">
                    <p>O pacote intermediário fornecerá acesso a cinco administradores, podendo cadastrar até doze projetos.</p>
                </div>
                <p><a class="btn" href="<?= $this->url(array('controller' => 'vendas', 'action' => 'index'), null, true) ?>">Compre Aqui! &raquo;</a></p>
            </div>
        </div>
    </div><!-- /.container -->
</div>