<br /><br />
<div id="view-content">
    <div class="container marketing">

        <br><br><br><br>
        <div class="row-fluid">
            <div class="col-md-4">
                <div class="img-test">
                    <img src="/TM-Estimates/public/img/pacbasic.jpg" alt="">
                </div>
                <h2>Básico</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn" href="<?= $this->url(array('controller' => 'identifica', 'action' => 'index'), null, true) ?>">Compre Aqui! &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <div class="img-test">
                    <img src="/TM-Estimates/public/img/pacinter.jpg" alt="">
                </div>
                <h2>Intermediário</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn" href="<?= $this->url(array('controller' => 'identifica', 'action' => 'index'), null, true) ?>">Compre Aqui! &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <div class="img-test">
                    <img src="/TM-Estimates/public/img/pacpremium.jpg" alt="">
                </div>
                <h2>Premium</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn" href="<?= $this->url(array('controller' => 'identifica', 'action' => 'index'), null, true) ?>">Compre Aqui! &raquo;</a></p>
            </div>
        </div>
    </div><!-- /.container -->
</div>