<br /><br />
<div id="view-content">
    <div class="row">
        <div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">
                    <br><br><br><br><br><br><br><br>
                    <h1>Sobre a empresa</h1>
                    <div class="text-justify">
                    <p>A empresa conta com uma equipe jovem e muito bem formada, com 
                        experiência em diversas áreas, tais como:
                        Conhecimento em bancos de dados SQL Server, MySQL, linguagens de 
                        programação Java, C, C#, PHP, Design usando CorelDRAW, experiência com
                        computadores de alta performance e experiência na Unidade de 
                        Desenvolvimento Organizacional da UESC.</p>
                    <p>Empresa Estimatech possui bastantes anos de experiências no mercado, oferecendo 
                        muitos outros serviços além da estimava de software. Em comparação não 
                        oferece uma ferramenta online para o cálculo de estimativas em projetos.
                    </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>