<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Nova Fase</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form role="form">
                        <div class="col-md-12">
                            <div class="form-group">
                                <!--<label>Descrição</label>-->
                                <input type="text" class="form-control" id="exampleInputDesc" name="Descri" placeholder="Descrição">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                            <a href="<?= $this->url(array('controller' => 'fase', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

