<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Funções de Transação</h3>
</div>
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'funcao-transacao', 'action' => 'novo'), null, true) ?>" class="btn btn btn-success" role="button">Novo</a>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Projeto</th>
                    <th>Função</th>
                    <th>Descrição</th>
                    <th>Qtd. Arquivos Referenciados</th>
                    <th>Qtd. Tipos de Dados</th>
                </tr>
            </thead>
            <tbody>
                 <?php foreach ($this->dados AS $key => $functranc): ?>
                    <tr>
                        <td><?= $functranc['idFuncaoTransacao'] ?></td>
                        <td><?= $functranc['projeto_idProjeto'] ?></td>
                        <td><?= $functranc['Funcao'] ?></td>
                        <td><?= $functranc['Descricao'] ?></td>
                        <td><?= $functranc['qtdArquivoRef'] ?></td>
                        <td><?= $functranc['qtdTipoDados'] ?></td>
                        <td><?= $functranc['PF'] ?></td>
                        <td><?php if($functranc['Complexidade'] == 1) echo 'Baixa';if($functranc['Complexidade'] == 2) echo 'Media';if($functranc['Complexidade'] == 3) echo 'Alta' ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'functranc', 'idP'=>$functranc['idFuncaoTransacao']), null, true) ?>">Editar</a></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'excluir-ft', 'idP'=>$functranc['idFuncaoTransacao']), null, true) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
