
<div id="view-content">

    <div class="cAlign" >


        <br /><br />
        <div id="menu">

            <ul class="nav nav-pills nav-divider" role="tablist">
                <li role="presentation"><a href="<?= $this->url(array('controller' => 'calendario', 'index' => 'index'), null, true) ?>">Janeiro</a></li>
                <li role="presentation" class="active"><a href="<?= $this->url(array('controller' => 'calendario', 'action' => 'fevereiro'), null, true) ?>">Fevereiro</a></li>
                   <li role="presentation"><a href="<?= $this->url(array('controller' => 'calendario', 'action' => 'marco'), null, true) ?>">Março</a></li>
                <li role="presentation"><a href="<?= $this->url(array('controller' => 'calendario', 'action' => 'abril'), null, true) ?>">Abril</a></li>
                <li role="presentation"><a href="#">Maio</a></li>
                <li role="presentation"><a href="#">Junho</a></li>
                <li role="presentation"><a href="#">Julho</a></li>
                <li role="presentation"><a href="#">Agosto</a></li>
                <li role="presentation"><a href="#">Setembro</a></li>
                <li role="presentation"><a href="#">Outubro</a></li>
                <li role="presentation"><a href="#">Novembro</a></li>
                <li role="presentation"><a href="#">Dezembro</a></li>
            </ul>

        </div>	
    </div>

    <form role="form">
        <div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>Calendário TM-Estimates 2014:</strong></h3>
                        </div>
                        <div class="panel-body">
                            <html><head><title>Calendario</title>
                                    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                                    <meta name="date.created" content="2014-11-03">
                                    <meta name="generator" content="HTML Calendar Maker 2.0">
                                    <meta name="licensekey" content="">
                                    <style type="text/css">
                                        /* Styling for the title (Month and Year) of the calendar */
                                        div.title {
                                            font: x-large Verdana, Arial, Helvetica, sans-serif;
                                            text-align: center;
                                            height: 50px;
                                            background-color: white;
                                            color: black;
                                        }
                                        /* Styling for the footer */
                                        div.footer {
                                            font: small Verdana, Arial, Helvetica, sans-serif;
                                            text-align: center;
                                        }
                                        /* Styling for the overall table */
                                        table {
                                            font: 100% Verdana, Arial, Helvetica, sans-serif;
                                            table-layout: fixed;
                                            border-collapse: collapse;
                                            width: 100%;
                                        }
                                        /* Styling for the column headers (days of the week) */
                                        th {
                                            padding: 0 0.5em;
                                            text-align: center;
                                            background-color:gray;
                                            color:white;
                                        }
                                        /* Styling for the individual cells (days) */
                                        td  {     
                                            font-size: medium;
                                            padding: 0.25em 0.25em;   
                                            width: 14%; 
                                            height: 70px;
                                            text-align: center;

                                        }
                                        /* Styling for the date numbers */
                                        .date  {     
                                            font-size: large;
                                            padding: 0.25em 0.25em;   
                                            text-align: center;
                                            vertical-align: top;
                                        }
                                        /* Class for individual days (coming in future release) */
                                        .sun {
                                            color:red;
                                        }
                                        /* Hide the month element (coming in future release) */
                                        th.month {
                                            visibility: hidden;
                                            display:none;
                                        }

                                    </style>
                                </head>
                                <body>
                                    <div class="title"><i>Fevereiro</i></div>
                                    <table border="2">
                                        <tr><th>Dom</th><th>Seg</th><th>Ter</th><th>Qua</th><th>Qui</th><th>Sex</th><th>Sab</th></tr>
                                        <tr><td><span class="date">&nbsp;</span></td><td><span class="date">&nbsp;</span></td><td><span class="date">&nbsp;</span></td><td><span class="date"></span></td><td><span class="date"></span></td><td><span class="date"></span></td><td><span class="date">1</span></td></tr>
                                        <tr><td><span class="date">2</span></td><td><span class="date">3</span></td><td><span class="date">4</span></td><td><span class="date">5</span></td><td><span class="date">6</span></td><td><span class="date">7</span></td><td><span class="date">8</span></td></tr>
                                        <tr><td><span class="date">9</span></td><td><span class="date">10</span></td><td><span class="date">11</span></td><td><span class="date">12</span></td><td><span class="date">13</span></td><td><span class="date">14</span></td><td><span class="date">15</span></td></tr>
                                        <tr><td><span class="date">16</span></td><td><span class="date">17</span></td><td><span class="date">18</span></td><td><span class="date">19</span></td><td><span class="date">20</span></td><td><span class="date">21</span></td><td><span class="date">22</span></td></tr>
                                        <tr><td><span class="date">23</span></td><td><span class="date">24</span></td><td><span class="date">25</span></td><td><span class="date">26</span></td><td><span class="date">27</span></td><td><span class="date">28</span></td><td><span class="date">&nbsp;</span></td></tr>
                                    </table>

                        </div>


                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
</div>



