<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Administradores</h3>
</div>    
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'novo-adm', 'action' => 'novo'), null, true) ?>">
            <button type="button" class="btn btn-success">Novo</button>
        </a>
        <button type="button" class="btn btn-primary">Editar</button>
        <button type="button" class="btn btn-danger">Excluir</button>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>Função</th>
                    <th>E-mail</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Sample</td>
                    <td>Filter</td>
                    <td>Desenvolvedor</td>
                    <td>OK</td>
                </tr>
                <tr>
                    <td>Try</td>
                    <td>It</td>
                    <td>Gerente</td>
                    <td>It</td>
                </tr>
                <tr>
                    <td>§</td>
                    <td>$</td>
                    <td>%</td>
                    <td>&</td>
                </tr>
            </tbody>
        </table>   
    </div>
</div>
