<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Ambiente</h3>
</div>    
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'ambiente', 'action' => 'novo'), null, true) ?>" class="btn btn btn-success" role="button">Novo</a>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Linguagem</th>
                    <th>Esforço (H/PF)</th>
                    <th>Produtividade (PF/H)</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados AS $key => $ambiente): ?>
                    <tr>
                        <td><?= $ambiente['idAmbiente'] ?></td>
                        <td><?= $ambiente['Linguagem'] ?></td>
                        <td><?= $ambiente['Esforco'] ?></td>
                        <td><?= $ambiente['Produtividade'] ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'ambiente', 'idP' => $ambiente['idAmbiente']), null, true) ?>">Editar</a></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'excluir-am', 'idP' => $ambiente['idAmbiente']), null, true) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
