<br /><br />
<div id="view-content">
	<br>
	<p><i><b><h2>Escolha seu pacote: </p></i></b></h2>
	<br><br>
    <img src="/TM-Estimates/public/img/pacbasic.jpg" alt="" height="120" width="100">        
	<p><b><h4><a style="color:#00ff00">Pacote Básico:</a></h4></b>
	<p><b>Descrição:</b> O pacote básico fornecerá acesso a um administrador,
		podendo cadastrar até três projetos.
	<p><b>Valor:</b>  R$ 60,00.
	<p><b>Tempo de uso:</b> 30 dias.
	<br><br>

	<img src="/TM-Estimates/public/img/pacinter.jpg" alt="" height="120" width="100">
	<p><b><h4><a style="color:#828282">Pacote Intermediário:</a></h4></b>
	<p><b>Descrição:</b> O pacote intermediário fornecerá acesso a três administrador, podendo cadastrar até oito projetos.
	<p><b>Valor:</b> R$ 110,00.
	<p><b>Tempo de uso:</b> 30 dias.
	<br><br>

	<img src="/TM-Estimates/public/img/pacpremium.jpg" alt="" height="120" width="100">
	<p><b><h4><a style="color:#ffd700">Pacote Premium:</a></h4></b>
	<p><b>Descrição:</b> O pacote intermediário fornecerá acesso a cinco administrador, podendo cadastrar até doze projetos.
	<p><b>Valor:</b> R$ 150,00.
	<p><b>Tempo de uso:</b> 45 dias.
	<br><br><br><br>


	<form>
		<b>Qual pacote deseja contratar?</b>
		<select name = "Pacotes">
			<option value="#" selected>Pacote Básico
			<option value="#" selected>Pacote Intermediario
				<option value="#" selected>Pacote Premium
				<br><br>

		</select>

	</form>
	<br>
	<div class="row">


	&nbsp&nbsp&nbsp
	
	
	<button type="button" class="btn btn-success" > Continuar </button>
	<div class="col-md-offset-10">
	<div class="col-md-2">	
		<br>
	<button type="button" class="btn btn-danger"> Cancelar </button>
</div></div></div>

	
<br><br>
</div>