
<div id="view-content">
	<br><br><br>
	<p><b><h3><i>Escolha a bandeira do seu cartão:<i></b></h3></p>

<form role="form">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <br><br><br>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Cartões de crédito:</strong></h3>
                    </div>
                    <div class="panel-body">

                        <label class="checkbox-inline">                  
                            <input type="radio" name="optionsRadios" id="visa" value="option1"  onclick="setVisa()">
                            <img src="/TM-Estimates/public/img/visa.jpg" alt="" height="50" width="65">                            
                        </label>


                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="master" value="option2" onclick="setMaster()">
                            <img src="/TM-Estimates/public/img/master.jpg" alt="" height="50" width="65">                            
                        </label>

                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="hiper" value="option3" onclick="setHiper()">
                            <img src="/TM-Estimates/public/img/hiper.jpg" alt="" height="50" width="65">                            
                        </label>

                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="america" value="option4" onclick="setAmerica()">
                            <img src="/TM-Estimates/public/img/america.jpg" alt="" height="50" width="65">                            
                        </label>


                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Cartão de débito ou Boleto:</strong></h3>
   </div>
                    <div class="panel-body">
                        
                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="visaE" value="option5" checked onclick="setVisaE()">
                            <img src="/TM-Estimates/public/img/visaE.jpg" alt="" height="50" width="65">                            
                        </label>

                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" 

id="boleto" value="option6" onclick="setBoleto()">
                            <img src="/TM-Estimates/public/img/boleto.jpg" alt="" height="50" width="65">                            
                        </label>



                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Escolha o seu Banco:</strong></h3>
 </div>
                    <div class="panel-body">

                            <div class="form-row">
                            <div class="col-md-6">
                                <label>Pagar pelo:</label>
                                <select class="form-control">
                                    <option value  = "1" class="form-

control">Banco do Brasil</option>
                                    <option value  = "2" class="form-

control"> Banco do Bradesco </option>
                                    <option value  = "3" class="form-

control"> Banco Santander </option>
                                    <option value  = "4" class="form-

control"> Banco do Itaú </option>
                                    <option value  = "5" class="form-

control"> Banco do Nordeste </option>
                                    
                                    <option value  = "6" class="form-

control"> Banco da Caixa </option>

                                </select>
                            </div>
 </div>
                    </div> <!-- .panel-body -->
                </div> <!-- .panel -->
            </div>
        </div>
    </div>




    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-

default">Pagar no seu Banco</button>
                <button type="button" class="btn btn-danger btn-

default" onclick="setCancel()">Cancelar</button>
            </div>
        </div>
    </div>

</form>
<br/><br/><br/>
</div>
</div>