<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Detalhar Fase</h3>
</div>
<div class="row">
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Descrição</th>
                    <th>Percentual</th>
                    <th>Dt. início (Prevista)</th>
                    <th>Dt. Finalização (Prevista)</th>
                    <th>Dt. início (Efetiva)</th>
                    <th>Dt. Finalização (Efetiva)</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados AS $key => $DetalharFase): ?>
                    <tr>
                        <td><?= $DetalharFase['idFase'] ?></td>
                        <td><?= $DetalharFase['Descricao'] ?></td>
                        <td><?= $DetalharFase['Percentual'] ?></td>
                        <td><?= $DetalharFase['datIniPrev'] ?></td>
                        <td><?= $DetalharFase['datFinPrev'] ?></td>
                        <td><?= $DetalharFase['datIniEfet'] ?></td>
                        <td><?= $DetalharFase['datFinEfet'] ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'detalhar-fase', 'idP'=>$DetalharFase['idFase']), null, true) ?>">Editar</a></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'excluir-dt-fa', 'idP'=>$DetalharFase['idFase']), null, true) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
