<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Detalhar Fase</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Fase</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Fases</label>
                                    <input type="number" class="form-control" id="exampleInputNumero" name="Numero" placeholder="Número">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Descrição</label>
                                    <input type="text" class="form-control" id="exampleInputDesc" name="Desc" placeholder="Descrição">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Percentual</label>
                                    <input type="number" class="form-control" id="exampleInputPer" name="Percentual" placeholder="Percentual">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. início (Prevista)</label>
                                    <input type="date" class="form-control" id="exampleInputDatIniPr" name="DatIniPre">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. Finalização (Prevista)</label>
                                    <input type="date" class="form-control" id="exampleInputDtFinPr" name="DatFinPre">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. início (Efetiva)</label>;
                                    <input type="date" class="form-control" id="exampleInputdtIniEf" name="DatIniEfe">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Dt. Finalização (Efetiva)</label>;
                                    <input type="date" class="form-control" id="exampleInputdtFinEf" name="DatFinEfe">
                                </div>
                            </div>

                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'Detalhar', 'action' => 'fases'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

