<br /><br /><br /><br /><br /><br />
<div id="view-content">
    <div class="row clearfix top-buffer">
        <div class="col-md-8">
            <div class="col-md-offset-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Login</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form"  method="post" action="<?= $this->url(array('controller' => 'login', 'action' => 'autentica'), null, true) ?>">
                            <div class="form-group">
                                <label for="InputEmail">Email</label>
                                <input required title="Endereço de Email" type="email" class="form-control" id="InputEmail" name="email" placeholder="Digite seu Email">
                            </div>
                            <div class="form-group">
                                <label for="InputPassword">Senha <a href="<?= $this->url(array('controller' => 'esqueceu-senha', 'action' => 'index'), null, true) ?>">(Esqueceu a senha)</a></label>
                                <input required type="password" class="form-control" id="InputPassword" name="senha" placeholder="Sua Senha" title="Mínimo de 6 dígitos" pattern=".{6,}">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Lembre-se de mim
                                </label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-default">Entrar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>