<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Colaboradores dos Projetos</h3>
</div> 
<div class="row">
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Projetos</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados AS $key => $colaboradores): ?>
                    <tr>
                        <td><?= $colaboradores['idColaboradores'] ?></td>
                        <td><?= $colaboradores['Nome'] ?></td>
                        <td><?= $colaboradores['Email'] ?></td>
                        <td><?= $colaboradores['idProjeto'] ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'colaboradores', 'idP' => $colaboradores['idColaboradores']), null, true) ?>">Editar</a></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'excluir-co', 'idP' => $colaboradores['idColaboradores']), null, true) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
