<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Funções de dados</h3>
</div>    
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'funcao-dados', 'action' => 'novo'), null, true) ?>" class="btn btn btn-success" role="button">Novo</a>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Projeto</th>
                    <th>Função</th>
                    <th>Descrição</th>
                    <th>Qtd. Tipos de registro</th>
                    <th>Qtd. Tipos de dados</th>
                    <th>Ponto de função</th>
                    <th>Complexidade</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados AS $key => $funcdados): ?>
                    <tr>
                        <td><?= $funcdados['idFuncaoDados'] ?></td>
                        <td><?= $funcdados['Titulo'] ?></td>
                        <td><?= $funcdados['Funcao'] ?></td>
                        <td><?= $funcdados['Descricao'] ?></td>
                        <td><?= $funcdados['qtdTiposRegistro'] ?></td>
                        <td><?= $funcdados['qtdTiposDados'] ?></td>
                        <td><?= $funcdados['PF'] ?></td>
                        <td><?php if($funcdados['Complexidade'] == 1) echo 'Baixa';if($funcdados['Complexidade'] == 2) echo 'Media';if($funcdados['Complexidade'] == 3) echo 'Alta' ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'funcdados', 'idP'=>$funcdados['idFuncaoDados']), null, true) ?>">Editar</a></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'excluir-fd', 'idP'=>$funcdados['idFuncaoDados']), null, true) ?>">Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
