<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Nova Função de dados</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Função de dados</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Projeto</label>
                                    <select required class="form-control" name="Projeto">
                                        <option value  = "" class="form-control"> </option>
                                        <?php foreach ($this->dados1 as $key => $value) { ?>
                                            <option value="<?= $value["idProjeto"] ?>" class="form-control"> <?= $value['Titulo'] ?> </option>
                                        <?php } ?>
                                    </select>
                                    <!--<input type="" class="form-control" id="exampleInputProj" placeholder="Projeto">-->
                                </div>
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Função</label>
                                <select required class="form-control">
                                    <option value  = "ALI" class="form-control"> ALI </option>
                                    <option value = "F" class="form-control"> AIE </option>
                                </select>
                            </div>

                            <div class="col-md-4">
                                <div required class="col-md-offset-0">
                                    <label>Descrição</label>
                                    <input type="text" class="form-control" id="exampleInputDesc" name="Descri" placeholder="Descrição">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Qtd. Tipos de registro</label>
                                    <input required type="number" class="form-control" id="exampleInputTipReg" name="TipRegis" placeholder="Quantidade de Tipos de registro">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Qtd. Tipos de dados</label>
                                    <input required type="number" class="form-control" id="exampleInputTipDad" name="TipDados" placeholder="Quantidades de Tipos de dados">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    
                                    <a href="<?= $this->url(array('controller' => 'funcao-dados', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

