<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Novo Administrador</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-11">
            <div class="col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Administradores</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Nome</label>
                                    <input type="text" class="form-control" id="exampleInputNome" name="Nome" placeholder="Nome">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="exampleInputEmail1">Email</label>
                                <input type="email" class="form-control" id="exampleInputEmail" name="Email" placeholder="Enter email">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label>Projeto</label>
                                    <input type="text" class="form-control" id="exampleInputProjeto" name="Projeto"placeholder="Projeto">
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <button type="submit" class="btn btn-danger btn-default">Cancelar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

