<br /><br /><br /><br /><br /><br />
<div id="view-content">
    <div class="container">
        <div class="row clearfix top-buffer">
            <div class="col-md-6">
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>Já sou cadastrado</strong></h3>
                        </div>
                        <div class="panel-body">
                            <form role="form"  method="post" action="<?= $this->url(array('controller' => 'login', 'action' => 'login'), null, true) ?>">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email</label>
                                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Senha <a href="<?= $this->url(array('controller' => 'esqueceu-senha', 'action' => 'index'), null, true) ?>">(Esqueceu a senha)</a></label>
                                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> Lembre-se de mim
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary btn-default">Entrar</button>
                            </form>
                        </div>
                    </div>
                    <br>
                </div>
            </div>

            <br>
        </div>

        <div class="row clearfix top-buffer">
            <div class="col-md-6">
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><strong>Já sou cadastrado</strong></h3>
                        </div>
                        <div class="panel-body">
                            <div class="col-md-6">
                                <div class="col-md-offset-8">
                                    <button type="submit" class="btn btn-primary btn-group-lg">Cadastre-se</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                    <br>
                </div>
            </div>

            <br>
        </div>
    </div>
</div>