<br><br>
<div id="view-content">
    <div class="row clearfix top-buffer">
        <br>
        <h1 class="text-center">SAC</h1>
        <br><br><br><br>
        <div class="col-md-4">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center"><strong><h2>Telefone</h2></strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group text-center">
                                <label><h3>(073) 3238-2477</h3></label>
                                <br>
                                <label><h3>(073) 9110-7667</h3></label>
                            </div>
                        </form>
                    </div>
                </div>
                <br>
            </div>
        </div>

        <div class="col-md-4">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center"><strong><h2>Email</h2></strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group text-center">
                                <label><h3>tmestimates@gmail.com</h3></label>
                                <br><br><br><br>
                            </div>
                        </form>
                    </div>
                </div>
                <br>
            </div>
        </div>

        <div class="col-md-4">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title text-center"><strong><h2>Endereço</h2></strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group text-center">
                                <label><h3>Praça 7 de Setembro, 84, Centro</h3></label>
                                <br>
                                <label><h3>Itajuípe, Bahia, 45630-000</h3></label>
                            </div>
                        </form>
                    </div>
                </div>
                <br>
            </div>
        </div>

    </div>