<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Novo Recurso</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Recurso</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'recurso', 'action' => 'salvar-dados'), null, true) ?>">
                            <div class="col-md-6">
                                <div class="col-md-offset-0">
                                    <label>Função</label>
                                    <input required type="text" class="form-control" name="descricao" placeholder="Função">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-offset-0">
                                    <label>Carga Horária/Dia</label>
                                    <input required type="number" class="form-control" name="carga_horaria" placeholder="0">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-offset-0">
                                    <label>Custo/Hora</label>
                                    <input required type="text" class="form-control" id="custo" name="custo">
                                </div>
                            </div>
                            <div class="col-md-6 form-groups">
                                <label>Nível</label>
                                <select required class="form-control">
                                    <option value  = "1" class="form-control text-center">1</option>
                                    <option value = "2" class="form-control text-center">2</option>
                                    <option value = "3" class="form-control text-center">3</option>
                                    <option value = "4" class="form-control text-center">4</option>
                                    <option value = "5" class="form-control text-center">5</option>
                                </select>
                            </div>
                            <br><br><br><br>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'recurso', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

