<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Projetos</h3>
</div>
<div class="row">
    <div class="col-md-3">
        <a href="<?= $this->url(array('controller' => 'projeto', 'action' => 'novo'), null, true) ?>" class="btn btn btn-success" role="button">Novo</a>
        <button type="button" class="btn btn-primary">Editar</button>
        <button type="button" class="btn btn-danger">Excluir</button>
    </div>
    <div class="col-md-3">
        <form action="#" method="get">
            <div class="input-group">
                <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
                <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-list-search">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Título</th>
                    <th>Categoria</th>
                    <th>Dt. Criação</th>
                    <th>Dt. Finalização</th>
                    <th>Situação</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->dados AS $key => $projeto): ?>
                    <tr>
                        <td><?= $projeto['idProjeto'] ?></td>
                        <td><?= $projeto['Titulo'] ?></td>
                        <td><?= $projeto['Categoria'] ?></td>
                        <td><?= $projeto['DataCriacao'] ?></td>
                        <td><?= $projeto['DataFininalizacao'] ?></td>
                        <td><?= $projeto['Situacao'] ?></td>
                        <td><a href="<?= $this->url(array('controller' => 'editar', 'action' => 'index', 'idP'=>$projeto['idProjeto']), null, true) ?>">Editar</a></td>
                        <td><a>Excluir</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>   
    </div>
</div>
