<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Novo Projeto</h3>
</div>
<div class="row">
<form role="form">
  
    <div class="form-group">
      <label for="NomeProjeto">Nome Projeto</label>
    <input type="text" class="form-control" id="exampleInputNome" placeholder="Insira Nome Projeto">
  </div>
  
    <div class="form-group">
    <label for="DataCricao">Data da Criação</label>
    <input type="datetime" class="form-control" id="exampleInputCriacao" >
  </div>
  
       
  
    <div class="form-group">
    <label for="DataFim">Data da Finalização</label>
    <input type="datetime" class="form-control" id="exampleInputFim" >
  </div>
    
    
    <div class="form-group">
      <label for="situacao">Situação</label>
    <input type="text" class="form-control" id="exampleInputSituacao" placeholder="Insira a situação">
  </div>
  
    <div class="form-group">
      <label for="cargahoraria">Carga Horaria</label>
    <input type="text" class="form-control" id="exampleInputSituacao" placeholder="Insira a Carga Horaria">
  </div>
  
    <div class="form-group">
      <label for="CustoHora">Custo Hora</label>;
    <input type="text" class="form-control" id="exampleInputSituacao" placeholder="Insira o Custo Hora">
  </div>
  
  
       
  <button type="submit" class="btn btn-default">Gravar</button>
</form>
</div>