<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Novo Projeto</h3>
</div>
<div class="row">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Projeto</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form" method="post" action="<?= $this->url(array('controller' => 'Preferencias', 'action' => 'get-Dados'), null, true) ?>">
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="NomeProjeto">Nome Projeto</label>
                                    <input type="text" class="form-control"  name="projetoTitulo" placeholder="Insira Nome Projeto">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="DataCricao">Data da Criação</label>
                                    <input type="date" class="form-control" name="projetoDataCriacao" >
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="DataFim">Data da Finalização</label>
                                    <input type="date" class="form-control" name="projetoDataFim" >
                                </div>
                            </div>
                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="situacao">Situação</label>
                                    <input type="text" class="form-control" name="projetoStatus" placeholder="Insira a situação">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="cargahoraria">Carga Horaria</label>
                                    <input type="time" class="form-control" id="exampleInputCargHor" placeholder="Insira a Carga Horaria">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <label for="CustoHora">Custo Hora</label>;
                                    <input type="text" class="form-control" id="exampleInputCustHor" placeholder="Insira o Custo Hora">
                                </div>
                            </div>

                            <br><br><br><br>
                            <div class="col-md-4">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success btn-default">Cadastrar</button>
                                    <a href="<?= $this->url(array('controller' => 'projeto', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

