<br /><br />
<div id="view-content">
	<br /><br /><br /><br />
<div id="view-content">
<div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Tipo de pessoa</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <label class="radio span4">
                        <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                        Pessoa Física
                        </label>
                        <label class="radio span4">
                          <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                          Pessoa Jurídica
                        </label>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Identificação</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Senha</label>
                                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            
                            <div class="form-group">
                                <label for="exampleInputPassword1">Confirme a senha</label>
                                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirme a senha">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Dados pessoais</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group">
                            <label>Nome</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nome Completo">
                            </div>
                            <div class="form-group">
                            <label>RG</label>
                            <input type="rg" class="form-control" id="exampleInputEmail1" placeholder="1111111111">
                            </div>
                            <div class="form-group">
                            <label>CPF</label>
                            <input type="cpf" class="form-control" id="exampleInputEmail1" placeholder="111.111.111-11">
                            </div>
                            <div class="form-group">
                            <label>Data de nascimento</label>
                            <input type="date" class="form-control" id="exampleInputEmail1" placeholder="DD/MM/AAAA">
                            </div>
                            <div class="form-group">
                            <label>Telefone</label>
                            <input type="tel" class="form-control" id="exampleInputEmail1" placeholder="(DDD) 1111-1111">
                            </div>
                            <div class="form-group">
                            <label>Celular</label>
                            <input type="tel" class="form-control" id="exampleInputEmail1" placeholder="(DDD) 1111-1111">
                            </div>
                            <div class="form-group">
                                <label>Sexo
                                <br/>
                                <select class="form-control">
                                <option value  = "M" class="form-control"> Masculino </option>
                                <option value = "F" class="form-control"> Femenino </option>
                                </label>
                            </div>

                          </select>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Endereço</strong></h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <div class="form-group">
                            <label>CEP</label>
                            <input type="cep" class="form-control" id="exampleInputEmail1" placeholder="11111-111">
                            </div>
                            <div class="form-group">
                            <label>Cidade</label>
                            <span class="form-control input-xlarge uneditable-input"></span>
                            </div>
                            <div class="form-group">
                            <label>Estado</label>
                            <span class="form-control input-xlarge uneditable-input"></span>
                            </div>
                            <div class="form-group">
                            <label>Rua</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Rua">
                            </div>
                            <div class="form-group">
                            <label>Nº</label>
                            <input type="number" class="form-control" id="exampleInputEmail1" placeholder="Nº">
                            </div>
                            <div class="form-group">
                            <label>Bairro</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Bairro">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<div id="view-content">
<div class="row clearfix top-buffer">
            <div class="col-md-10">
                <div class="col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-default">Cadastrar</button>
                <button type="submit" class="btn btn-danger btn-default">Cancelar</button>
                </div>
            </div>
</div>
</div>
<br/><br/><br/>



