<br /><br /><br /><br />
<form role="form">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <label><h1>Cadastro de Pessoa Física</h1></label>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Tipo de pessoa</strong></h3>
                    </div>
                    <div class="panel-body">
                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked onclick="setPF()">
                            Pessoa Física
                        </label>
                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="pj" value="option2" onclick="setPJ()">
                            Pessoa Jurídica
                        </label>
                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Identificação</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <label for="exampleInputEmail1">Email</label>
                            <input type="email" class="form-control" id="InputEmail" placeholder="Enter email">
                        </div>
                        <div class="col-md-4">
                            <label for="exampleInputPassword1">Senha</label>
                            <input type="password" class="form-control" id="InputPassword1" placeholder="Password">
                        </div>
                        <div class="col-md-4">
                            <label for="exampleInputPassword1">Confirme a senha</label>
                            <input type="password" class="form-control" id="InputPassword2" placeholder="Confirme a senha">
                        </div>
                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Dados pessoais</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-row">
                            <div class="col-md-12 form-group">
                                <label>Nome</label>
                                <input type="text" class="form-control" id="InputNome" placeholder="Nome Completo">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4 form-groups">
                                <label>RG</label>
                                <input type="rg" class="form-control" id="InputRG" placeholder="1111111111">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>CPF</label>
                                <input type="cpf" class="form-control" id="InputCPF" placeholder="111.111.111-11">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Data de nascimento</label>
                                <input type="date" class="form-control" id="InputDatNasc" placeholder="DD/MM/AAAA">
                            </div>
                        </div>
                        <br /><br /><br /><br /><br /><br /><br />
                        <div class="form-row">
                            <div class="col-md-4">
                                <label>Telefone</label>
                                <input type="tel" class="form-control" id="InputTel" placeholder="(DDD) 1111-1111">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Celular</label>
                                <input type="tel" class="form-control" id="InputCel" placeholder="(DDD) 1111-1111">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Sexo</label>
                                <select class="form-control">
                                    <option value  = "M" class="form-control"> Masculino </option>
                                    <option value = "F" class="form-control"> Femenino </option>
                                </select>
                            </div>
                        </div>
                    </div> <!-- .panel-body -->
                </div> <!-- .panel -->
            </div>
        </div>
    </div>


    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Endereço</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <label>CEP</label>
                            <input type="cep" class="form-control" id="exampleInputEnd" placeholder="11111-111">
                        </div>
                        <div class="col-md-4">
                            <label>Cidade</label>
                            <span class="form-control input-xlarge uneditable-input"></span>
                        </div>
                        <div class="col-md-4">
                            <label>Estado</label>
                            <span class="form-control input-xlarge uneditable-input"></span>
                        </div>
                        <br/><br/><br/><br/>
                        <div class="col-md-4">
                            <label>Rua</label>
                            <input type="text" class="form-control" id="exampleInputRua" placeholder="Rua">
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label>Nº</label>
                                <input type="number" class="form-control" id="exampleInputNum" placeholder="Nº">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label>Bairro</label>
                                <input type="text" class="form-control" id="exampleInputBairro" placeholder="Bairro">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-default">Cadastrar</button>
                <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
            </div>
        </div>
    </div>

</form>
<br/><br/><br/>



