<br /><br /><br /><br />
<form role="form" method="post" action="<?= $this->url(array('controller' => 'cadastro-user', 'action' => 'cadastrar'), null, true) ?>">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <label><h1>Cadastro de Pessoa Física</h1></label>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Tipo de pessoa</strong></h3>
                    </div>
                    <div class="panel-body">
                        <label class="checkbox-inline">
                            <input type="radio" name="radio_box" value="pf" checked onclick="setPF()">
                            Pessoa Física
                        </label>
                        <label class="checkbox-inline">
                            <input type="radio" name="radio_box" value="pj" onclick="setPJ()">
                            Pessoa Jurídica
                        </label>
                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Identificação</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <label for="exampleInputEmail1">Email</label>
                            <input type="email" class="form-control" name="email" placeholder="Enter email">
                        </div>
                        <div class="col-md-4">
                            <label for="exampleInputPassword1">Senha</label>
                            <input type="password" class="form-control" name="senha" placeholder="Password">
                        </div>
                        <div class="col-md-4">
                            <label for="exampleInputPassword1">Confirme a senha</label>
                            <input type="password" class="form-control" name="ConfSenha" placeholder="Confirme a senha">
                        </div>
                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Dados pessoais</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-row">
                            <div class="col-md-4 form-group">
                                <label>Nome</label>
                                <input type="text" class="form-control" name="nome" placeholder="Nome">
                            </div>
                            <div class="col-md-8 form-group">
                                <label>Sobrenome</label>
                                <input type="text" class="form-control" name="sobrenome" placeholder="Sobrenome">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4 form-groups">
                                <label>RG</label>
                                <input type="rg" class="form-control" name="rg" placeholder="1111111111">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>CPF</label>
                                <input type="cpf" class="form-control" name="cpf" placeholder="111.111.111-11">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Data de nascimento</label>
                                <input type="date" class="form-control" name="datNasc" placeholder="DD/MM/AAAA">
                            </div>
                        </div>
                        <br /><br /><br /><br /><br /><br /><br />
                        <div class="form-row">
                            <div class="col-md-4">
                                <label>Telefone</label>
                                <input type="tel" class="form-control" name="tel" placeholder="(DDD) 1111-1111">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Celular</label>
                                <input type="tel" class="form-control" name="cel" placeholder="(DDD) 1111-1111">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>Sexo</label>
                                <select class="form-control">
                                    <option selected="" value="" name="sexo">Selecione o Sexo</option>
                                    <option value="M">Masculino</option>
                                    <option value="F">Feminino</option>
                                    <option value="F">Outros </option>
                                </select>
                            </div>
                        </div>
                    </div> <!-- .panel-body -->
                </div> <!-- .panel -->
            </div>
        </div>
    </div>


    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Endereço</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <label>CEP</label>
                            <input type="cep" class="form-control" name="cep" placeholder="11111-111">
                        </div>
                        <div class="col-md-4">
                            <label>Cidade</label>
                            <input type="cep" class="form-control" name="cidade" placeholder="11111-111">
                        </div>
                        <div class="col-md-4">
                            <label>Estado</label>
<!--                            <span class="form-control input-xlarge uneditable-input"></span>-->
                            <select name="estado"  class="form-control">
                                <option selected="" value="">Selecione o Estado (UF)</option>
                                <option value="Acre">Acre</option>
                                <option value="Alagoas">Alagoas</option>
                                <option value="Amapá">Amapá</option>
                                <option value="Amazonas">Amazonas</option>
                                <option value="Bahia">Bahia</option>
                                <option value="Ceará">Ceará</option>
                                <option value="Distrito Federal">Distrito Federal</option>
                                <option value="Espírito Santo">Espírito Santo</option>
                                <option value="Goiás">Goiás</option>
                                <option value="Maranhão">Maranhão</option>
                                <option value="Mato Grosso">Mato Grosso</option>
                                <option value="Mato Grosso do Sul">Mato Grosso do Sul</option>
                                <option value="Minas Gerais">Minas Gerais</option>
                                <option value="Pará">Pará</option>
                                <option value="Paraíba">Paraíba</option>
                                <option value="Paraná">Paraná</option>
                                <option value="Pernambuco">Pernambuco</option>
                                <option value="Piauí">Piauí</option>
                                <option value="Rio de Janeiro">Rio de Janeiro</option>
                                <option value="Rio Grande do Sul">Rio Grande do Sul</option>
                                <option value="Rio Grande do Norte">Rio Grande do Norte</option>
                                <option value="Rondônia">Rondônia</option>
                                <option value="Roraima">Roraima</option>
                                <option value="Santa Catarina">Santa Catarina</option>
                                <option value="São Paulo">São Paulo</option>
                                <option value="Sergipe">Sergipe</option>
                                <option value="Tocantins">Tocantins</option>
                            </select>
                        </div>
                        <br/><br/><br/><br/>
                        <div class="col-md-4">
                            <label>Rua</label>
                            <input type="text" class="form-control" name="rua" placeholder="Rua">
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label>Nº</label>
                                <input type="number" class="form-control" name="numero" placeholder="Nº">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label>Bairro</label>
                                <input type="text" class="form-control" name="bairro" placeholder="Bairro">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-default">Cadastrar</button>
                <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
            </div>
        </div>
    </div>

</form>
<br/><br/><br/>



