<br /><br /><br /><br />
<form role="form" method="post" name="cadastro" action="<?= $this->url(array('controller' => 'cadastro-user', 'action' => 'cadastrar'), null, true) ?>">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <label><h1>Cadastro de Pessoa Jurídica</h1></label>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Tipo de pessoa</strong></h3>
                    </div>
                    <div class="panel-body">
                        <label class="checkbox-inline">
                            <input type="radio" name="radio_box" id="optionsRadios1" value="pf" onclick="setPF()">
                            Pessoa Física
                        </label>
                        <label class="checkbox-inline">
                            <input type="radio" name="radio_box" id="optionsRadios2" value="pj" checked onclick="setPJ()">
                            Pessoa Jurídica
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer" onload="confirma_pass()">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Identificação</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label for="email">Email</label>
                                <input required type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label for="senha">Senha</label>
                                <input required type="password" class="form-control" name="senha" placeholder="Senha"
                                       onchange="this.setCustomValidity(this.validity.patternMismatch ? this.title : '');
                                               if (this.checkValidity())
                                                   form.ConfSenha.pattern = this.value;">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-offset-0">
                                <label for="ConfSenha">Confirme a senha</label>
                                <input required type="password" class="form-control" id="ConfSenha" name="ConfSenha" placeholder="Confirme a senha"
                                       onchange="this.setCustomValidity(this.validity.patternMismatch ? this.title : '');">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Dados Empresarial</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>CNPJ</label>
                                    <input required id="cnpj" class="form-control" name="cnpj" placeholder="CNPJ">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Razão Social</label>
                                    <input required type="text" class="form-control" name="razSocial" placeholder="Razão Social">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Nome Fantasia</label>
                                    <input required type="text" class="form-control" name="nomeFant" placeholder="Nome Fantasia">
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Telefone</label>
                                    <input type="tel" id="tel" class="form-control" name="tel">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Endereço</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>CEP</label>
                                    <input required type="cep" id="cep" class="form-control" name="cep">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Cidade</label>
                                    <input required type="cidade" class="form-control" name="cidade" placeholder="cidade">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Estado</label>
                                    <!--<span class="form-control input-xlarge uneditable-input"></span>-->
                                    <select required name="estado"  class="form-control">
                                        <option selected="" value="">Selecione o Estado (UF)</option>
                                        <option value="ac">Acre</option>
                                        <option value="al">Alagoas</option>
                                        <option value="am">Amazonas</option>
                                        <option value="ap">Amapá</option>
                                        <option value="ba">Bahia</option>
                                        <option value="ce">Ceará</option>
                                        <option value="df">Distrito Federal</option>
                                        <option value="es">Espírito Santo</option>
                                        <option value="go">Goiás</option>
                                        <option value="ma">Maranhão</option>
                                        <option value="mt">Mato Grosso</option>
                                        <option value="ms">Mato Grosso do Sul</option>
                                        <option value="mg">Minas Gerais</option>
                                        <option value="pa">Pará</option>
                                        <option value="pb">Paraíba</option>
                                        <option value="pr">Paraná</option>
                                        <option value="pe">Pernambuco</option>
                                        <option value="pi">Piauí</option>
                                        <option value="rj">Rio de Janeiro</option>
                                        <option value="rn">Rio Grande do Norte</option>
                                        <option value="ro">Rondônia</option>
                                        <option value="rs">Rio Grande do Sul</option>
                                        <option value="rr">Roraima</option>
                                        <option value="sc">Santa Catarina</option>
                                        <option value="se">Sergipe</option>
                                        <option value="sp">São Paulo</option>
                                        <option value="to">Tocantins</option> 
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Rua</label>
                                    <input required type="text" class="form-control" name="rua" placeholder="Rua">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Nº</label>
                                    <input type="number" class="form-control" name="numero" placeholder="Nº">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Bairro</label>
                                    <input required type="text" class="form-control" name="bairro" placeholder="Bairro">
                                </div>
                            </div>
                            <br/><br/><br/><br/>
                            <div class="col-md-12">
                                <div class="col-md-offset-0">
                                    <label>Complemento</label>
                                    <input type="text" class="form-control" name="complemento" placeholder="Complemento">
                                </div>
                            </div>
                            <br/><br/><br/><br/><br/><br/><br/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-default">Cadastrar</button>
                <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index'), null, true) ?>" class="btn btn-danger btn-default" role="button">Cancelar</a>
            </div>
        </div>
    </div>
</form>

<br/><br/><br/>
