<br /><br />
<div id="view-content">
	<br><br><br>
	<p><b><h3><i>Escolha a bandeira do seu cartão:<i></b></h3></p>

<form role="form">
    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <br><br><br>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Cartões de crédito:</strong></h3>
                    </div>
                    <div class="panel-body">

                        <label class="checkbox-inline">                  
                            <input type="radio" name="optionsRadios" id="visa" value="option1" checked onclick="setVisa()">
                            <img src="img/visa.jpg" alt="" height="50" width="65">                            
                        </label>


                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="master" value="option2" onclick="setMaster()">
                            <img src="img/master.jpg" alt="" height="50" width="65">                            
                        </label>

                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="hiper" value="option3" onclick="setHiper()">
                            <img src="img/hiper.jpg" alt="" height="50" width="65">                            
                        </label>

                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="america" value="option4" onclick="setAmerica()">
                            <img src="img/america.jpg" alt="" height="50" width="65">                            
                        </label>


                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Cartão de débito ou Boleto:</strong></h3>
                    </div>
                    <div class="panel-body">
                        
                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="visaE" value="option5" onclick="setVisaE()">
                            <img src="img/visaE.jpg" alt="" height="50" width="65">                            
                        </label>

                        <label class="checkbox-inline">
                            <input type="radio" name="optionsRadios" id="boleto" value="option6" onclick="setBoleto()">
                            <img src="img/boleto.jpg" alt="" height="50" width="65">                            
                        </label>



                    </div>
                </div> <!-- .panel -->
            </div>
        </div>
    </div>

    <div class="row clearfix top-buffer">
        <div class="col-md-10">
            <div class="col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Dados do Cartão:</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-row">
                            <div class="col-md-4 form-group">
                                <label>Número do cartão:</label>
                                <input type="text" class="form-control" id="InputNumero" placeholder=" &nbsp&nbsp&nbsp&nbsp&nbsp XXXX XXXX XXXX XXXX">
                            </div>                            
                        </div>


						
                        <div class="form-row">
                        <div class="col-md-10 form-group">
                        </div>
                        </div>
                                              

                        <div class="form-row">
                            <div class="col-md-8 form-groups">
                                <label>Nome do títular do cartão:</label>
                                <input type="text" class="form-control" id="InputTitular" placeholder="Como está gravado no cartão">
                            </div>

                            <div class="form-row">
                        <div class="col-md-10 form-group">
                        </div>
                        </div>                           
                        

                           <div class="form-row">
                            <div class="col-md-4">
                                <label>Validade do cartão:</label>
                                <input type="text" class="form-control" id="InputMes" placeholder="Mês">
                            </div>
                            <div class="col-md-4 form-groups">
                                <label>&nbsp</label>
                                <input type="text" class="form-control" id="InputAno" placeholder="Ano">
                            </div>

                            <div class="form-row">
                        <div class="col-md-10 form-group">
                        </div>
                        </div> 

                            <div class="col-md-4 form-groups">
                                <label>Código de segurança do cartão:</label>
                                <input type="text" class="form-control" id="InputCod" placeholder=" XXX">
                                <br>
                                <img src="img/codigo.jpg" alt="" height="120" width="180">
                            </div>

                            <div class="form-row">
                        <div class="col-md-10 form-group">
                        </div>
                        </div> 

                            <div class="form-row">
                            <div class="col-md-6">
                                <label>Pagar em:</label>
                                <select class="form-control">
                                    <option value  = "1" class="form-control"> 1 x de R$     , sem juros </option>
                                    <option value  = "2" class="form-control"> 2 x de R$     , sem juros </option>
                                    <option value  = "3" class="form-control"> 3 x de R$     , sem juros </option>
                                    <option value  = "4" class="form-control"> 4 x de R$     , sem juros </option>
                                    <option value  = "5" class="form-control"> 5 x de R$     , sem juros </option>

                                </select>
                            </div>
                            
                            






                        </div>
                    </div> <!-- .panel-body -->
                </div> <!-- .panel -->
            </div>
        </div>
    </div>




    <div class="row clearfix top-buffer">
        <div class="col-md-12">
            <div class="col-md-offset-2">
                <button type="submit" class="btn btn-primary btn-default">Finlizar compra</button>
                <button type="submit" class="btn btn-danger btn-default">Cancelar</button>
            </div>
        </div>
    </div>

</form>
<br/><br/><br/>


</div>