<div class="page-header">
    <h3><span class="glyphicon glyphicon-th-list"></span> Contagem</h3>
</div>
<div id="view-content">
    <ul class="nav nav-pills nav-divider" role="tablist">
        <li role="presentation" class="active"><a href="#">Indicativa</a></li>
        <li role="presentation"><a href="#">Detalhada</a></li>
        <li role="presentation"><a href="#">Estimada</a></li>
    </ul>
</div>